CREATE TABLE ROL (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(200),
    ACTIVO BIT NOT NULL
);
CREATE TABLE EVENTO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR (200),
    AFORO INT NOT NULL,
    ACTIVO BIT NOT NULL
);
CREATE TABLE USUARIO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CEDULA VARCHAR(200) NOT NULL,
    NOMBRE VARCHAR (200) NOT NULL,
    APELLIDO1 VARCHAR (200) NOT NULL,
    APELLIDO2 VARCHAR (200),
    TELEFONO VARCHAR(200) NOT NULL,
    CORREO VARCHAR(200) NOT NULL,
    ID_ROL INT NOT NULL,
    ACTIVO BIT NOT NULL
);
CREATE TABLE LISTA (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_EVENTO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    ACTIVO BIT NOT NULL
);
ALTER TABLE USUARIO ADD FOREIGN KEY (ID_ROL) REFERENCES ROL(ID);
ALTER TABLE LISTA ADD FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID);
ALTER TABLE LISTA ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID);