CREATE DATABASE MUNITRA;
USE MUNITRA;

CREATE TABLE DEPARTAMENTO(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL
);
CREATE TABLE PROVINCIA (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(10) NOT NULL
);
CREATE TABLE CANTON (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (30) NOT NULL,
    ID_PROVINCIA INT NOT NULL,
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID)
);
CREATE TABLE DISTRITO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (30) NOT NULL,
    ID_CANTON INT NOT NULL,
    FOREIGN KEY (ID_CANTON) REFERENCES CANTON (ID)
);
CREATE TABLE BARRIO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (30) NOT NULL,
    ID_DISTRITO INT NOT NULL,
    FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO (ID)
);
CREATE TABLE IDENTIFICACION (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (30) NOT NULL
);
CREATE TABLE TIPO_CAMPO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (30) NOT NULL,
    FORMATO_CAMPO VARCHAR(50),
    TIPO_COBRO VARCHAR(50)
);
CREATE TABLE TIPO_REQUISITO(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (30) NOT NULL,
    ID_TIPO_CAMPO INT NOT NULL,
    FOREIGN KEY (ID_TIPO_CAMPO) REFERENCES TIPO_CAMPO (ID)
);
CREATE TABLE USUARIO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (200) NOT NULL,
    CORREO VARCHAR (200) NOT NULL,
    CLAVE VARCHAR (200) NOT NULL,
    ESTADO VARCHAR (200) NOT NULL
);
/*Locaciones*/
INSERT INTO PROVINCIA (NOMBRE) VALUES ('San José');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Alajuela');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Cartago');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Heredia');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Guanacaste');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Puntarenas');
/*Tipos de Identificación*/
INSERT INTO IDENTIFICACION (NOMBRE) VALUES ('Cédula de identidad');
INSERT INTO IDENTIFICACION (NOMBRE) VALUES ('Pasaporte');
INSERT INTO IDENTIFICACION (NOMBRE) VALUES ('Cédula de residencia');
INSERT INTO IDENTIFICACION (NOMBRE) VALUES ('Número interno');
INSERT INTO IDENTIFICACION (NOMBRE) VALUES ('Número asegurado');
INSERT INTO IDENTIFICACION (NOMBRE) VALUES ('DIMEX');
INSERT INTO IDENTIFICACION (NOMBRE) VALUES ('NITE');
INSERT INTO IDENTIFICACION (NOMBRE) VALUES ('DIDI');