/*Locaciones*/
INSERT INTO PROVINCIA (NOMBRE) VALUES ('San José');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Alajuela');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Cartago');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Heredia');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Guanacaste');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Puntarenas');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Limón');

INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('San José', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Escazú', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Desamparados', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Puriscal', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Tarrazú', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Aserrí', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Mora', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Goicoechea', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Santa Ana', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Alajuelita', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Vázquez de Coronado', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Acosta', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Tibás', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Moravia', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Montes de Oca', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Turrubares', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Dota', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Curridabat', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Pérez Zeledón', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('León Cortés', 1);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Alajuela', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('San Ramón', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Grecia', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('San Mateo', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Atenas', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Naranjo', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Palmares', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Poás', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Orotina', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('San Carlos', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Zarcero', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Valverde Vega', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Upala', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Los Chiles', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Guatuso', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Río Cuarto', 2);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Cartago', 3);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Paraíso', 3);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('La Unión', 3);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Jiménez', 3);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Turrialba', 3);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Alvarado', 3);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Oreamuno', 3);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('El Guarco', 3);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Heredia', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Barva', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Santo Domingo', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Santa Bárbara', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('San Rafael', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('San Isidro', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Belén', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Flores', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('San Pablo', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Sarapiquí', 4);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Liberia', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Nicoya', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Santa Cruz', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Bagaces', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Carrillo', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Cañas', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Abangares', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Tilarán', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Nandayure', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('La Cruz', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Hojancha', 5);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Puntarenas', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Esparza', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Buenos Aires', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Montes de Oro', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Osa', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Quepos', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Golfito', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Coto Brus', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Parrita', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Corredores', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Garabito', 6);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Limón', 7);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Pococí', 7);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Siquirres', 7);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Talamanca', 7);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Matina', 7);
INSERT INTO CANTON (NOMBRE, ID_PROVINCIA) VALUES ('Guácimo', 7);

-- Distritos del cantón de San José (ID_CANTON = 1, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Carmen', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Merced', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Catedral', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Hospital', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Zapote', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Sebastián', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Pavas', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Hatillo', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Francisco de Dos Ríos', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Uruca', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Mata Redonda', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Uruca', 1, 1);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Rohrmoser', 1, 1);

-- Distritos del cantón de Escazú (ID_CANTON = 2, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Escazú', 1, 2);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Antonio', 1, 2);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Rafael', 1, 2);

-- Distritos del cantón de Desamparados (ID_CANTON = 3, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Desamparados', 1, 3);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Miguel', 1, 3);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan de Dios', 1, 3);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Rafael Arriba', 1, 3);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Antonio', 1, 3);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Cristóbal', 1, 3);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Rosario', 1, 3);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Gravilias', 1, 3);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Patarrá', 1, 3);

-- Distritos del cantón de Puriscal (ID_CANTON = 4, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Puriscal', 1, 4);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Barbacoas', 1, 4);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Grifo Alto', 1, 4);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cruz', 1, 4);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Desamparaditos', 1, 4);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Rafael', 1, 4);

-- Distritos del cantón de Tarrazú (ID_CANTON = 5, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Marcos', 1, 5);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Lorenzo', 1, 5);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Sebastián', 1, 5);

-- Distritos del cantón de Aserrí (ID_CANTON = 6, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Aserrí', 1, 6);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Gabriel', 1, 6);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Vuelta de Jorco', 1, 6);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Lucha', 1, 6);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tarrazú', 1, 6);

-- Distritos del cantón de Mora (ID_CANTON = 7, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Mora', 1, 7);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Guayabo', 1, 7);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Colón', 1, 7);

-- Distritos del cantón de Goicoechea (ID_CANTON = 8, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Goicoechea', 1, 8);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Felipe', 1, 8);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 1, 8);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Calle Blancos', 1, 8);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Las Cañas', 1, 8);

-- Distritos del cantón de Santa Ana (ID_CANTON = 9, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santa Ana', 1, 9);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Pozos', 1, 9);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Uruca', 1, 9);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Salitral', 1, 9);

-- Distritos del cantón de Alajuelita (ID_CANTON = 10, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Alajuelita', 1, 10);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Antonio', 1, 10);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Concepción', 1, 10);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Felipe', 1, 10);

-- Distritos del cantón de Vázquez de Coronado (ID_CANTON = 11, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Vázquez de Coronado', 1, 11);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 1, 11);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Rafael', 1, 11);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan de Dios', 1, 11);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Delicias', 1, 11);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Jaris', 1, 11);

-- Distritos del cantón de Acosta (ID_CANTON = 12, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Ignacio', 1, 12);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Guaitil', 1, 12);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tres Ríos', 1, 12);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Concepción', 1, 12);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Francisco', 1, 12);

-- Distritos del cantón de Tibás (ID_CANTON = 13, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tibás', 1, 13);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan', 1, 13);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Anselmo Llorente', 1, 13);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Carmen', 1, 13);

-- Distritos del cantón de Moravia (ID_CANTON = 14, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Moravia', 1, 14);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Cruz', 1, 14);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Jerónimo', 1, 14);

-- Distritos del cantón de Montes de Oca (ID_CANTON = 15, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Pedro', 1, 15);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Sabanilla', 1, 15);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Montes de Oca', 1, 15);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Ojo de Agua', 1, 15);

-- Distritos del cantón de Turrubares (ID_CANTON = 16, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Pablo', 1, 16);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Pedro', 1, 16);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Rafael', 1, 16);

-- Distritos del cantón de Dota (ID_CANTON = 17, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 1, 17);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Jardín', 1, 17);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Rivas', 1, 17);

-- Distritos del cantón de Curridabat (ID_CANTON = 18, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Curridabat', 1, 18);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Granadilla', 1, 18);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Sánchez', 1, 18);

-- Distritos del cantón de Pérez Zeledón (ID_CANTON = 19, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 1, 19);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Daniel Flores', 1, 19);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Rivas', 1, 19);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Gerardo de Rivas', 1, 19);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Platanares', 1, 19);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Peñas Blancas', 1, 19);

-- Distritos del cantón de León Cortés (ID_CANTON = 20, ID_PROVINCIA = 1)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Pablo', 1, 20);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Ramón', 1, 20);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Antonio', 1, 20);

-- Distritos del cantón de Alajuela (ID_CANTON = 21, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Alajuela', 2, 21);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San José', 2, 21);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Carrizal', 2, 21);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santiago', 2, 21);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Roble', 2, 21);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Fortuna', 2, 21);

-- Distritos del cantón de San Ramón (ID_CANTON = 22, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Ramón', 2, 22);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 2, 22);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Ángeles', 2, 22);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Alfaro', 2, 22);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Concepción', 2, 22);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Piedades', 2, 22);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Zapotal', 2, 22);

-- Distritos del cantón de Grecia (ID_CANTON = 23, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Grecia', 2, 23);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 2, 23);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan', 2, 23);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Sarchí Norte', 2, 23);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Sarchí Sur', 2, 23);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tacares', 2, 23);

-- Distritos del cantón de San Mateo (ID_CANTON = 24, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Mateo', 2, 24);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Jesús', 2, 24);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Concepción', 2, 24);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Desmonte', 2, 24);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Lima', 2, 24);

-- Distritos del cantón de Atenas (ID_CANTON = 25, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Atenas', 2, 25);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Jesús', 2, 25);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 2, 25);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Concepción', 2, 25);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santa Eulalia', 2, 25);

-- Distritos del cantón de Naranjo (ID_CANTON = 26, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Naranjo', 2, 26);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San José', 2, 26);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Palmeras', 2, 26);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Manzano', 2, 26);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cirrí Sur', 2, 26);

-- Distritos del cantón de Palmares (ID_CANTON = 27, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Palmares', 2, 27);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Zaragoza', 2, 27);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Desamparaditos', 2, 27);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Granja', 2, 27);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Lima', 2, 27);

-- Distritos del cantón de Poás (ID_CANTON = 28, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Poás', 2, 28);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Pedro', 2, 28);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan de Poás', 2, 28);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Carrillos', 2, 28);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Bajo Rodríguez', 2, 28);

-- Distritos del cantón de Orotina (ID_CANTON = 29, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Orotina', 2, 29);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Ceiba', 2, 29);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Hacienda Vieja', 2, 29);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Desamparados', 2, 29);

-- Distritos del cantón de San Carlos (ID_CANTON = 30, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Ciudad Quesada', 2, 30);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan de San Carlos', 2, 30);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Aguas Zarcas', 2, 30);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Venecia', 2, 30);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cote', 2, 30);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Florencia', 2, 30);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Tigra', 2, 30);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Tanque', 2, 30);

-- Distritos del cantón de Zarcero (ID_CANTON = 31, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Zarcero', 2, 31);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tacares', 2, 31);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Fortuna', 2, 31);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Paz', 2, 31);

-- Distritos del cantón de Valverde Vega (ID_CANTON = 32, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santiago', 2, 32);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Vicente', 2, 32);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Jerónimo', 2, 32);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Marcos', 2, 32);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santa Rosa', 2, 32);

-- Distritos del cantón de Upala (ID_CANTON = 33, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Upala', 2, 33);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San José', 2, 33);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Delicias', 2, 33);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Aguas Claras', 2, 33);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Castillo', 2, 33);

-- Distritos del cantón de Los Chiles (ID_CANTON = 34, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Los Chiles', 2, 34);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cabo Velas', 2, 34);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Fortuna', 2, 34);

-- Distritos del cantón de Guatuso (ID_CANTON = 35, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Guatuso', 2, 35);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Rafael', 2, 35);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Bosque', 2, 35);

-- Distritos del cantón de Río Cuarto (ID_CANTON = 36, ID_PROVINCIA = 2)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Río Cuarto', 2, 36);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Cuesta', 2, 36);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Rosario', 2, 36);

-- Distritos del cantón de Cartago (ID_CANTON = 37, ID_PROVINCIA = 3)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cartago', 3, 37);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Oriental', 3, 37);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Occidental', 3, 37);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Carmen', 3, 37);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Nicolás', 3, 37);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Francisco', 3, 37);

-- Distritos del cantón de Paraíso (ID_CANTON = 38, ID_PROVINCIA = 3)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Paraíso', 3, 38);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cachí', 3, 38);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Llanos de Santa Lucía', 3, 38);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Rafael', 3, 38);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tuis', 3, 38);

-- Distritos del cantón de La Unión (ID_CANTON = 39, ID_PROVINCIA = 3)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Diego', 3, 39);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Ramón', 3, 39);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tres Ríos', 3, 39);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Río Azul', 3, 39);

-- Distritos del cantón de Jiménez (ID_CANTON = 40, ID_PROVINCIA = 3)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Juan Viñas', 3, 40);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tucurrique', 3, 40);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Concepción', 3, 40);

-- Distritos del cantón de Turrialba (ID_CANTON = 41, ID_PROVINCIA = 3)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Turrialba', 3, 41);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Suiza', 3, 41);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santa Teresita', 3, 41);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Peralta', 3, 41);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tuis', 3, 41);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Villas de las Palmas', 3, 41);

-- Distritos del cantón de Alvarado (ID_CANTON = 42, ID_PROVINCIA = 3)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Pacayas', 3, 42);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San José', 3, 42);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Río Blanco', 3, 42);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cebadilla', 3, 42);

-- Distritos del cantón de Oreamuno (ID_CANTON = 43, ID_PROVINCIA = 3)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Rafael', 3, 43);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santa Rosa', 3, 43);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan', 3, 43);

-- Distritos del cantón de El Guarco (ID_CANTON = 44, ID_PROVINCIA = 3)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Tejar', 3, 44);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 3, 44);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cipreses', 3, 44);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Juan Viñas', 3, 44);

-- Distritos del cantón de Heredia (ID_CANTON = 45, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Heredia', 4, 45);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Mercedes', 4, 45);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Francisco', 4, 45);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Ulloa', 4, 45);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Vara Blanca', 4, 45);

-- Distritos del cantón de Barva (ID_CANTON = 46, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Barva', 4, 46);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San José de la Montaña', 4, 46);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santa Lucía', 4, 46);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Pedro', 4, 46);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan de Mata', 4, 46);

-- Distritos del cantón de Santo Domingo (ID_CANTON = 47, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santo Domingo', 4, 47);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Vicente', 4, 47);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Miguel', 4, 47);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santiago', 4, 47);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Gloria', 4, 47);

-- Distritos del cantón de Santa Bárbara (ID_CANTON = 48, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santa Bárbara', 4, 48);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Dulce Nombre', 4, 48);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santiago', 4, 48);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Pedro', 4, 48);

-- Distritos del cantón de San Rafael (ID_CANTON = 49, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Rafael', 4, 49);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 4, 49);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Virgen', 4, 49);

-- Distritos del cantón de San Isidro (ID_CANTON = 50, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 4, 50);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Atenas', 4, 50);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan', 4, 50);

-- Distritos del cantón de Belén (ID_CANTON = 51, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Belén', 4, 51);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Ribera', 4, 51);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Antonio', 4, 51);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Barrial', 4, 51);

-- Distritos del cantón de Flores (ID_CANTON = 52, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Flores', 4, 52);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Joaquín', 4, 52);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Ceiba', 4, 52);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Francisco', 4, 52);

-- Distritos del cantón de San Pablo (ID_CANTON = 53, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Pablo', 4, 53);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Toro', 4, 53);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Ceiba', 4, 53);

-- Distritos del cantón de Sarapiquí (ID_CANTON = 54, ID_PROVINCIA = 4)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Puerto Viejo', 4, 54);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Virgen', 4, 54);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Horquetas', 4, 54);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cureña', 4, 54);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Llanos de San Ramón', 4, 54);
-- Distritos del cantón de Liberia (ID_CANTON = 55, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Liberia', 5, 55);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cañas', 5, 55);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Nacascolo', 5, 55);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Curubandé', 5, 55);

-- Distritos del cantón de Nicoya (ID_CANTON = 56, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Nicoya', 5, 56);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Antonio', 5, 56);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Nosara', 5, 56);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Belén', 5, 56);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Quebrada Honda', 5, 56);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Sámara', 5, 56);

-- Distritos del cantón de Santa Cruz (ID_CANTON = 57, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santa Cruz', 5, 57);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Diriá', 5, 57);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Bolsón', 5, 57);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cabo Velas', 5, 57);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Veintisiete de Abril', 5, 57);

-- Distritos del cantón de Bagaces (ID_CANTON = 58, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Bagaces', 5, 58);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Fortuna', 5, 58);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Medea', 5, 58);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Canalete', 5, 58);

-- Distritos del cantón de Carrillo (ID_CANTON = 59, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Carrillo', 5, 59);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Filadelfia', 5, 59);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Sardinal', 5, 59);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Sonzapote', 5, 59);

-- Distritos del cantón de Cañas (ID_CANTON = 60, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cañas', 5, 60);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Palmira', 5, 60);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Porozal', 5, 60);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Antonio', 5, 60);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San José', 5, 60);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cañas Dulces', 5, 60);

-- Distritos del cantón de Abangares (ID_CANTON = 61, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Abangares', 5, 61);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan', 5, 61);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Las Juntas', 5, 61);

-- Distritos del cantón de Tilarán (ID_CANTON = 62, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tilarán', 5, 62);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Quebrada Grande', 5, 62);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Lagarto', 5, 62);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Bajo Cacao', 5, 62);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Isla Chira', 5, 62);

-- Distritos del cantón de Nandayure (ID_CANTON = 63, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Carmen', 5, 63);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Diriá', 5, 63);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Limonal', 5, 63);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santo Domingo', 5, 63);

-- Distritos del cantón de La Cruz (ID_CANTON = 64, ID_PROVINCIA = 5)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Cruz', 5, 64);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Santa Cecilia', 5, 64);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cabo Blanco', 5, 64);

-- Distritos del cantón de Puntarenas (ID_CANTON = 65, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Puntarenas', 6, 65);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Chacarita', 6, 65);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Roble', 6, 65);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Isla', 6, 65);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Pochote', 6, 65);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Pitahaya', 6, 65);

-- Distritos del cantón de Esparza (ID_CANTON = 66, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Esparza', 6, 66);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('El Cayó', 6, 66);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Juan Grande', 6, 66);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Isla del Coco', 6, 66);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Ramón', 6, 66);

-- Distritos del cantón de Buenos Aires (ID_CANTON = 67, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Buenos Aires', 6, 67);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Isidro', 6, 67);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Volcán', 6, 67);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Puerto Cortés', 6, 67);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Palmar Norte', 6, 67);

-- Distritos del cantón de Montes de Oro (ID_CANTON = 68, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Montes de Oro', 6, 68);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Miramar', 6, 68);

-- Distritos del cantón de Osa (ID_CANTON = 69, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Osa', 6, 69);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Palmar', 6, 69);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Canoas', 6, 69);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Rincón', 6, 69);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Piedras Blancas', 6, 69);

-- Distritos del cantón de Quepos (ID_CANTON = 70, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Quepos', 6, 70);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Aguas Claras', 6, 70);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Quepos', 6, 70);

-- Distritos del cantón de Golfito (ID_CANTON = 71, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Golfito', 6, 71);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Puerto Jiménez', 6, 71);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cabo Blanco', 6, 71);

-- Distritos del cantón de Coto Brus (ID_CANTON = 72, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Coto Brus', 6, 72);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('San Vito', 6, 72);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Las Lajas', 6, 72);

-- Distritos del cantón de Parrita (ID_CANTON = 73, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Parrita', 6, 73);

-- Distritos del cantón de Corredores (ID_CANTON = 74, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Corredores', 6, 74);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Cuesta', 6, 74);

-- Distritos del cantón de Garabito (ID_CANTON = 75, ID_PROVINCIA = 6)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Garabito', 6, 75);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Jacó', 6, 75);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Tárcoles', 6, 75);

-- Distritos del cantón de Limón (ID_CANTON = 76, ID_PROVINCIA = 7)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Limón', 7, 76);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('La Colina', 7, 76);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Río Blanco', 7, 76);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Matina', 7, 76);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Las Brisas', 7, 76);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Pococí', 7, 76);

-- Distritos del cantón de Pococí (ID_CANTON = 77, ID_PROVINCIA = 7)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Pococí', 7, 77);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Río Frío', 7, 77);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Guápiles', 7, 77);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cariari', 7, 77);

-- Distritos del cantón de Siquirres (ID_CANTON = 78, ID_PROVINCIA = 7)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Siquirres', 7, 78);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Jiménez', 7, 78);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Pacuarito', 7, 78);

-- Distritos del cantón de Talamanca (ID_CANTON = 79, ID_PROVINCIA = 7)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Talamanca', 7, 79);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Bratsi', 7, 79);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Cahuita', 7, 79);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Puerto Viejo', 7, 79);

-- Distritos del cantón de Matina (ID_CANTON = 80, ID_PROVINCIA = 7)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Matina', 7, 80);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Batán', 7, 80);

-- Distritos del cantón de Guácimo (ID_CANTON = 81, ID_PROVINCIA = 7)
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Guácimo', 7, 81);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Mercedes', 7, 81);
INSERT INTO DISTRITO (NOMBRE, ID_PROVINCIA, ID_CANTON) VALUES ('Río Jiménez', 7, 81);